# Generated by Django 3.0.7 on 2020-07-09 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='map',
            name='rasters',
            field=models.ManyToManyField(blank=True, to='maps.RasterLayer'),
        ),
        migrations.AddField(
            model_name='map',
            name='vectors',
            field=models.ManyToManyField(blank=True, to='maps.VectorLayer'),
        ),
    ]
