# Generated by Django 3.0.7 on 2020-09-05 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obs', '0005_auto_20200905_1455'),
        ('posts', '0003_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.AlterField(
            model_name='post',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obs.Project'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='body',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
