# Generated by Django 3.0.7 on 2020-08-02 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obs', '0003_auto_20200729_2002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='ObsComment',
        ),
        migrations.DeleteModel(
            name='PointSite',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='parentobs',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='type',
        ),
        migrations.AddField(
            model_name='observation',
            name='obs_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_type', to='obs.ObservationType'),
        ),
        migrations.AddField(
            model_name='observationtype',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
