# Generated by Django 3.0.7 on 2020-09-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs', '0004_auto_20200801_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='obs_types',
        ),
        migrations.AddField(
            model_name='project',
            name='guidelines',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='obscomment',
            name='body',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='observationtype',
            name='slug',
            field=models.CharField(blank=True, help_text='No spaces, will be the name of the Vue component', max_length=30, null=True),
        ),
    ]
