# Generated by Django 3.0.7 on 2020-09-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs', '0006_auto_20200905_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='obs_types',
            field=models.ManyToManyField(blank=True, to='obs.ObservationType'),
        ),
        migrations.AlterField(
            model_name='observationtype',
            name='slug',
            field=models.CharField(blank=True, help_text='No spaces, will be the PascalCase name of the Vue component, such as PastureMove', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='guidelines',
            field=models.TextField(blank=True, help_text='Guidelines for submitting observations, data, and posts', max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='members_only',
            field=models.BooleanField(default=True, help_text='In order to post observations, you must have joined and been accepted into that project. For members-only projects, only members can view the data.'),
        ),
    ]
