# Generated by Django 3.0.7 on 2020-07-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('entered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'resources',
                'ordering': ['-id'],
            },
        ),
    ]
